import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { NextUIProvider } from "@nextui-org/react";
import "./globals.css";

const montserrat = Montserrat({
	subsets: ["latin"],
	fallback: ["Arial", "sans-serif"],
});

export const metadata: Metadata = {
	title: "ARS | Advanced Robotics Systems",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={montserrat.className}>
				<NextUIProvider>{children}</NextUIProvider>
			</body>
		</html>
	);
}
